server.port=8080
#spring.application.name=camel-credit-demo
spring.application.name=credit
camel.component.kafka.brokers=localhost:9092

hawtio.authenticationEnabled=false
management.endpoints.web.exposure.include=*
management.endpoint.hawtio.enabled=true


